#
# © 2024-present https://github.com/cengiz-pz
#

pluginNodeName=NotificationScheduler
pluginModuleName=notification_scheduler
pluginPackage=org.godotengine.plugin.notification
pluginVersion=5.2
godotVersion=4.6
godotReleaseType=stable
extra.resultClass=org.godotengine.plugin.notification.ResultActivity
extra.notificationReceiverClass=org.godotengine.plugin.notification.NotificationReceiver
extra.cancelReceiverClass=org.godotengine.plugin.notification.CancelNotificationReceiver
extra.bootReceiverClass=org.godotengine.plugin.notification.BootReceiver
gradle.icons=icons.gradle.kts
