#
# © 2026-present Godot Mobile Plugins (https://github.com/godot-mobile-plugins)
#

pluginNodeName=NotificationScheduler
pluginModuleName=notification_scheduler
pluginPackage=org.godotengine.plugin.notification
pluginVersion=6.0
